Adding dapr
testcontainers/community-module-registry pull request #15
Opened 2023-10-24 09:20 UTC by salaboy

Including svn and png

2023-10-27 10:27 UTC, kiview requested changes

2023-10-27 10:27 UTC, kiview commented on modules/dapr.md
> +      var dapr = new DaprContainer();
```suggestion
      var dapr = new DaprContainer("daprio/daprd:1.12.0");
```

The constructor does not exist. Does this take make sense?

2023-10-29 07:57 UTC, salaboy commented on modules/dapr.md
> +      var dapr = new DaprContainer();
Yes.. let's use that

2023-10-30 08:30 UTC, kiview approved these changes

2023-10-30 08:30 UTC, merged