Add WireMock module to the registry
testcontainers/community-module-registry pull request #3
Opened 2023-06-07 22:04 UTC by oleg-nenashev

FTR https://github.com/wiremock/wiremock-testcontainers-java/issues/53 for tracking on the WireMock side

2023-06-07 22:18 UTC, eddumelendez requested changes
Thanks for submitting WireMock to the Module Catalog, @oleg-nenashev ! I've left some suggestions

2023-06-07 22:18 UTC, eddumelendez commented on modules/wiremock.md
> +        }
Just to be consistent with the other examples

```suggestion
      WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
                .withMapping("hello", WireMockContainerJunit5Test.class, "hello-world.json");
      wiremockServer.start();                
```

2023-06-07 22:18 UTC, eddumelendez commented on modules/wiremock.md
> +  - other
I think the right would be
```suggestion
  - web
```

2023-06-07 22:18 UTC, eddumelendez commented on modules/wiremock.md
> +    This module allows provisioning the WireMock server as a standalone container within your unit test,
```suggestion
    This module allows provisioning the WireMock server as a standalone container within your tests,
```

2023-06-08 08:00 UTC, oleg-nenashev commented
Hi! Is it required to use just a single category? The fact is that the
module is used for Web API testing, for Cloud API testing and cloud service
integration (WireMock Cloud), and also as a developer tool for many other
cases. So all three categories fit

P.S: A "developer_tools" category would be nice

On Thu, 8 Jun 2023, 00:19 Eddú Meléndez Gonzales, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for submitting WireMock to the Module Catalog, @oleg-nenashev
> <https://github.com/oleg-nenashev> ! I've left some suggestions
> ------------------------------
>
> In modules/wiremock.md
> <https://github.com/testcontainers/community-module-registry/pull/3#discussion_r1222236992>
> :
>
> > +        import org.junit.jupiter.api.*;
> +        import org.testcontainers.junit.jupiter.*;
> +        import org.wiremock.integrations.testcontainers.testsupport.http.*;
> +
> +        import static org.assertj.core.api.Assertions.assertThat;
> +
> +        @Testcontainers
> +        class WireMockContainerJunit5Test {
> +
> +            @Container
> +            WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
> +                    .withMapping("hello", WireMockContainerJunit5Test.class, "hello-world.json");
> +
> +            @Test
> +            void helloWorld() throws Exception {
> +                String url = wiremockServer.getUrl("/hello");
> +                HttpResponse response = new TestHttpClient().get(url);
> +                assertThat(response.getBody())
> +                        .as("Wrong response body")
> +                        .contains("Hello, world!");
> +            }
> +        }
>
> Just to be consistent with the other examples
> ⬇️ Suggested change
>
> -        import org.junit.jupiter.api.*;
> -        import org.testcontainers.junit.jupiter.*;
> -        import org.wiremock.integrations.testcontainers.testsupport.http.*;
> -
> -        import static org.assertj.core.api.Assertions.assertThat;
> -
> -        @Testcontainers
> -        class WireMockContainerJunit5Test {
> -
> -            @Container
> -            WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
> -                    .withMapping("hello", WireMockContainerJunit5Test.class, "hello-world.json");
> -
> -            @Test
> -            void helloWorld() throws Exception {
> -                String url = wiremockServer.getUrl("/hello");
> -                HttpResponse response = new TestHttpClient().get(url);
> -                assertThat(response.getBody())
> -                        .as("Wrong response body")
> -                        .contains("Hello, world!");
> -            }
> -        }
> +      WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
> +                .withMapping("hello", WireMockContainerJunit5Test.class, "hello-world.json");
> +      wiremockServer.start();
>
> ------------------------------
>
> In modules/wiremock.md
> <https://github.com/testcontainers/community-module-registry/pull/3#discussion_r1222237194>
> :
>
> > +  - cloud
> +  - web
> +  - other
>
> I think the right would be
> ⬇️ Suggested change
>
> -  - cloud
> -  - web
> -  - other
> +  - web
>
> ------------------------------
>
> In modules/wiremock.md
> <https://github.com/testcontainers/community-module-registry/pull/3#discussion_r1222237914>
> :
>
> > +            @Container
> +            WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
> +                    .withMapping("hello", WireMockContainerJunit5Test.class, "hello-world.json");
> +
> +            @Test
> +            void helloWorld() throws Exception {
> +                String url = wiremockServer.getUrl("/hello");
> +                HttpResponse response = new TestHttpClient().get(url);
> +                assertThat(response.getBody())
> +                        .as("Wrong response body")
> +                        .contains("Hello, world!");
> +            }
> +        }
> +      ```
> +description: |
> +    This module allows provisioning the WireMock server as a standalone container within your unit test,
>
> ⬇️ Suggested change
>
> -    This module allows provisioning the WireMock server as a standalone container within your unit test,
> +    This module allows provisioning the WireMock server as a standalone container within your tests,
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/testcontainers/community-module-registry/pull/3#pullrequestreview-1468673067>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW4RIAPRT3IOYEWIXF6AR3XKD46BANCNFSM6AAAAAAY6O23MY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-06-08 10:41 UTC, eddumelendez commented
> Is it required to use just a single category?

Not really but can not find another example with multiple categories. I think in this case we are talking about the WireMock itself and its scope and not about how it is provided (Cloud service). Thinking again about `cloud` category, I'm not quite sure TBH because it's not like `LocalStack`.

2023-06-08 13:22 UTC, oleg-nenashev commented
>  Thinking again about cloud category, I'm not quite sure TBH because it's not like LocalStack.

But there is WireMock Cloud

2023-06-09 12:48 UTC, kiview commented
Our current `cloud` category means tools, that allow the "emulation"/built-in-mocking of cloud services. That's not the kind of service WireMock Cloud provides, right?

Out of consistency with the other tags, just going with `web` is probably the best approach, but I am sure this can evolve in the future (and it is all a bit fuzzy and subjective after all).

2023-06-09 12:49 UTC, kiview approved these changes

2023-06-09 15:42 UTC, oleg-nenashev commented
> Our current cloud category means tools, that allow the "emulation"/built-in-mocking of cloud services. That's not the kind of service WireMock Cloud provides, right?

Actually even WireMock Does it @kiview . For example, see https://library.wiremock.org/cloud/ for the ready-to-fly stubs for mocking Cloud Services :)

2023-06-09 15:43 UTC, oleg-nenashev commented on modules/wiremock.md
> +  - other
As a suggested compromise, I will remove "other"

```suggestion
  - cloud
  - web
```

2023-06-09 15:59 UTC, eddumelendez approved these changes

2023-06-09 15:59 UTC, merged

2023-06-09 16:43 UTC, eddumelendez commented
Thanks, @oleg-nenashev ! WireMock is listed in the Module Registry now https://testcontainers.com/modules/wiremock/