fix(mosquitto): module name
testcontainers/community-module-registry pull request #97
Opened 2024-11-23 09:28 UTC by crankcase

There is typos in documentation and problem with naming convention of mosquitto module in testcontainers-python.

I have prepare RP to fix name https://github.com/testcontainers/testcontainers-python/pull/740

Once it will be merged, documentation should be updated

Thanks!

2024-12-05 08:55 UTC, mdelapenya commented
Could you resolve conflicts 🙏 ? Then we can proceed with the merge

2025-02-06 06:56 UTC, mdelapenya requested changes
Left a few comments that need to be resolved before accepting these changes

2025-02-06 06:56 UTC, mdelapenya commented on modules/mosquitto/index.md
> +    url: https://testcontainers-python.readthedocs.io/en/latest/modules/mosquitto/README.html
I think this URL is correct, so I'm not sure of the validity of this PR.

2025-02-06 06:56 UTC, mdelapenya commented on modules/mosquitto/index.md
> +      pip install testcontainers[mosquitto]
question: could you point me to the pip link to install the package so I can verify if this change is also needed? I was not able to locate it myself 😞

2025-02-06 20:31 UTC, alexanderankin commented on modules/mosquitto/index.md
> +      pip install testcontainers[mosquitto]
the "extra" which is `mqtt` today and is being requested to be changed to `mosquitto` in the docs above is in fact listed here - https://github.com/testcontainers/testcontainers-python/blob/9317736c34cbe23844006c8e49629fc88e142949/pyproject.toml#L146

2025-02-06 21:07 UTC, eddumelendez commented on modules/mosquitto/index.md
> +    url: https://testcontainers-python.readthedocs.io/en/latest/modules/mosquitto/README.html
https://github.com/testcontainers/testcontainers-python/pull/740 suggests to rename the module. If so, then this change applies.

2025-05-26 17:01 UTC, closed without merging